# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - gm130s@gmail.com
env:
  matrix:
    - USE_DEB=true  ROS_DISTRO="indigo"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - USE_DEB=true  ROS_DISTRO="indigo"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu  
                    ABICHECK_URL='github:ros-perception/image_pipeline#indigo'
    - USE_DEB=true  ROS_DISTRO="indigo"   PRERELEASE=true  PRERELEASE_DOWNSTREAM_DEPTH=2
    - USE_DEB=true  ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - USE_DEB=true  ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu  
                    ABICHECK_URL='github:ros-perception/image_pipeline#indigo'
    - USE_DEB=true  ROS_DISTRO="kinetic"  PRERELEASE=true  PRERELEASE_DOWNSTREAM_DEPTH=2
    - USE_DEB=true  ROS_DISTRO="lunar"    ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - USE_DEB=true  ROS_DISTRO="lunar"    ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu  
                    ABICHECK_URL='github:ros-perception/image_pipeline#indigo'
    - USE_DEB=true  ROS_DISTRO="lunar"    PRERELEASE=true  PRERELEASE_DOWNSTREAM_DEPTH=2
matrix:
  allow_failures:
    - env: USE_DEB=true  ROS_DISTRO="indigo"   PRERELEASE=true  PRERELEASE_DOWNSTREAM_DEPTH=2
    - env: USE_DEB=true  ROS_DISTRO="kinetic"  PRERELEASE=true  PRERELEASE_DOWNSTREAM_DEPTH=2
    - env: USE_DEB=true  ROS_DISTRO="lunar"    PRERELEASE=true  PRERELEASE_DOWNSTREAM_DEPTH=2

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
  - .ci_config/travis.sh

